# Generated by Django 4.2.5 on 2024-11-17 20:48

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('psychoapp', '0002_historiaclinica'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('symptoms', djongo.models.fields.JSONField()),
                ('recommendation', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'symptom_log',
            },
        ),
    ]
